# Generated by Django 3.2 on 2023-08-20 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("codes", "0002_auto_20230820_2152"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="code",
            table="codes_code",
        ),
    ]
