# Generated by Django 3.2 on 2023-08-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codes", "0003_alter_code_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodesCode",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("d_codigo", models.CharField(max_length=200)),
                ("d_asenta", models.CharField(max_length=200)),
                ("d_tipo_asenta", models.CharField(max_length=200)),
                ("d_mnpio", models.CharField(db_column="D_mnpio", max_length=200)),
                ("d_estado", models.CharField(max_length=200)),
                ("d_ciudad", models.CharField(max_length=200)),
                ("d_cp", models.CharField(db_column="d_CP", max_length=200)),
                ("c_estado", models.CharField(max_length=200)),
                ("c_oficina", models.CharField(max_length=200)),
                ("c_cp", models.CharField(db_column="c_CP", max_length=200)),
                ("c_tipo_asenta", models.CharField(max_length=200)),
                ("c_mnpio", models.CharField(max_length=200)),
                ("id_asenta_cpcons", models.CharField(max_length=200)),
                ("d_zona", models.CharField(max_length=200)),
                ("c_cve_ciudad", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "codes_code",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Code",
        ),
    ]
