# Generated by Django 3.2 on 2023-08-20 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("codes", "0004_auto_20230820_2217"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CodesCode",
        ),
    ]
